// ortho_len6 -- exhaustive census of the SHORT kernel elements of
//
//        rho_a : W_n  -->>  W(a) <= Isom(R^n),
//
// the surjection from the right-angled Coxeter envelope on the orthogonality graph of the
// right-corner orthoscheme O(a_1,...,a_n) onto the group generated by its n+1 facet
// reflections.
//
// WHAT IT SETTLES.  Let K(a) = min{ length(w) : w in ker rho_a, w != 1 }.  The paper proves
// K(a) >= 6 always, and the rank-two classification produces a kernel element of length 6
// exactly when three consecutive legs are equal (t(a) >= 1) and one of length 8 when an
// endpoint pair is equal and no triple exists (t(a)=0, e(a)>=1).  The value left open was
// whether a kernel element of length 6 can lie OUTSIDE every rank-two standard parabolic,
// which would drop K(a) to 6 on the (e>=1, t=0) stratum.  This program decides that question
// exhaustively on a stated box of leg tuples.
//
// METHOD.  A kernel element of length exactly 6 is w = uv with u,v reduced of length 3 and
// rho_a(u) = rho_a(v)^{-1}; conversely any two distinct elements of W_n of length <= 3 with the
// same image produce a nontrivial kernel element of length <= 6.  So it suffices to enumerate
// the reduced words of length <= 3, compute their images exactly, and inspect the collisions.
// There are only (n+1)(1+n+n^2) such words, so the whole ball-of-radius-3 census costs a few
// hundred matrix products per leg tuple, and the box can be pushed far.
//
// EXACTNESS.  The legs are positive integers (every positive rational tuple scales to one, and
// rho_a(w) = 1 is scale invariant).  Each facet reflection is stored as an INTEGER homogeneous
// (n+1) x (n+1) matrix M with bottom row (0,...,0,D), representing x |-> (Sx + b)/D:
//
//   R_0 : hyperplane {x_1 = a_1},  normal e_1,                      D = 1, b = 2 a_1 e_1
//   R_j : hyperplane through 0,    normal a_{j+1} e_j - a_j e_{j+1}, D = a_j^2 + a_{j+1}^2
//   R_n : hyperplane {x_n = 0},    normal e_n,                      D = 1, b = 0
//
// so products are exact integer matrix products, and rho_a(w) = 1 is the exact test
// M[r][c] = 0 (r != c), M[r][r] = M[n][n], M[r][n] = 0.  Entries are i128 and every product is
// range-checked; the program aborts rather than wrap.
//
// REDUCED WORDS IN W_n.  W_n is the right-angled Coxeter group on the graph with an edge
// whenever |i-j| >= 2.  A word is reduced iff there is no pair of positions j < k carrying the
// same letter with every letter strictly between commuting with it (the deletion condition for
// graph products); deleting such a pair shortens the word by 2 without changing the element.
// `reduce` iterates that deletion, so `reduce(u ++ reverse(v))` is empty exactly when u and v
// are the same element of W_n, and otherwise its length and support are the invariants of the
// kernel element uv^{-1}.
//
// Rule 8: memory is O(words per tuple) = a few hundred matrices, peak RSS a few MB; run under
// runcap.sh anyway.
//
// Usage:  ortho_len6 <n> <L> [--quiet]
//         sweeps every primitive tuple in {1..L}^n.

use std::env;

// ---------------------------------------------------------------- integer helpers

#[inline]
fn cmul(a: i128, b: i128) -> i128 {
    match a.checked_mul(b) {
        Some(v) => v,
        None => panic!("i128 overflow in multiply: {} * {}", a, b),
    }
}
#[inline]
fn cadd(a: i128, b: i128) -> i128 {
    match a.checked_add(b) {
        Some(v) => v,
        None => panic!("i128 overflow in add"),
    }
}
fn gcd(a: i128, b: i128) -> i128 {
    let (mut a, mut b) = (a.abs(), b.abs());
    while b != 0 {
        let t = a % b;
        a = b;
        b = t;
    }
    a
}
fn gcd64(a: i64, b: i64) -> i64 {
    let (mut a, mut b) = (a.abs(), b.abs());
    while b != 0 {
        let t = a % b;
        a = b;
        b = t;
    }
    a
}

// ---------------------------------------------------------------- W_n word combinatorics

#[inline]
fn commutes(i: usize, j: usize) -> bool {
    (i as i64 - j as i64).abs() >= 2
}

/// Reduce a word in W_n by the deletion condition.  Returns the reduced word.
fn reduce(w: &[usize]) -> Vec<usize> {
    let mut v: Vec<usize> = w.to_vec();
    'outer: loop {
        for j in 0..v.len() {
            for k in (j + 1)..v.len() {
                if v[j] != v[k] {
                    continue;
                }
                if ((j + 1)..k).all(|m| commutes(v[m], v[j])) {
                    v.remove(k);
                    v.remove(j);
                    continue 'outer;
                }
            }
        }
        return v;
    }
}

fn support(w: &[usize]) -> Vec<usize> {
    let mut s: Vec<usize> = w.to_vec();
    s.sort_unstable();
    s.dedup();
    s
}

/// Is `w` of the form (R_i R_{i+1})^3, i.e. the rank-two relator of a pi/3 dihedral pair?
fn is_rank_two_hexagon(w: &[usize]) -> bool {
    if w.len() != 6 {
        return false;
    }
    let s = support(w);
    if s.len() != 2 {
        return false;
    }
    if s[1] != s[0] + 1 {
        return false;
    }
    // alternating
    (0..6).all(|k| w[k] == w[k % 2])
}

// ---------------------------------------------------------------- the representation

struct Rep {
    n: usize,
    dim: usize,          // n+1, homogeneous
    gens: Vec<Vec<i128>>, // (n+1) generators, each dim*dim
}

impl Rep {
    fn new(a: &[i64]) -> Rep {
        let n = a.len();
        let dim = n + 1;
        let mut gens = Vec::with_capacity(n + 1);
        for j in 0..=n {
            // normal m_j in coordinates x_0..x_{n-1}  (x_{k-1} <-> e_k)
            let mut m = vec![0i128; n];
            if j == 0 {
                m[0] = 1;
            } else if j == n {
                m[n - 1] = 1;
            } else {
                m[j - 1] = a[j] as i128; //  a_{j+1}
                m[j] = -(a[j - 1] as i128); // -a_j
            }
            let d: i128 = m.iter().map(|x| x * x).sum();
            let mut mat = vec![0i128; dim * dim];
            for r in 0..n {
                for c in 0..n {
                    let mut v = if r == c { d } else { 0 };
                    v -= 2 * m[r] * m[c];
                    mat[r * dim + c] = v;
                }
            }
            mat[dim * dim - 1] = d;
            if j == 0 {
                // translation 2 a_1 e_1, scaled by D = 1
                mat[0 * dim + n] = 2 * a[0] as i128;
            }
            gens.push(mat);
        }
        Rep { n, dim, gens }
    }

    fn mul(&self, x: &[i128], y: &[i128], out: &mut [i128]) {
        let d = self.dim;
        for r in 0..d {
            for c in 0..d {
                let mut s: i128 = 0;
                for k in 0..d {
                    s = cadd(s, cmul(x[r * d + k], y[k * d + c]));
                }
                out[r * d + c] = s;
            }
        }
    }

    fn is_identity(&self, m: &[i128]) -> bool {
        let d = self.dim;
        let n = self.n;
        let lam = m[d * d - 1];
        if lam == 0 {
            return false;
        }
        for r in 0..n {
            if m[r * d + n] != 0 {
                return false;
            }
            for c in 0..n {
                let want = if r == c { lam } else { 0 };
                if m[r * d + c] != want {
                    return false;
                }
            }
        }
        true
    }

    /// divide out the content and fix the sign of the homogeneous scale
    fn normalize(&self, m: &mut [i128]) {
        let mut g: i128 = 0;
        for v in m.iter() {
            g = gcd(g, *v);
        }
        if g == 0 {
            return;
        }
        if m[self.dim * self.dim - 1] < 0 {
            g = -g;
        }
        for v in m.iter_mut() {
            *v /= g;
        }
    }
}

// ---------------------------------------------------------------- per-tuple census

struct Finding {
    len: usize,
    supp: usize,
    word: Vec<usize>,
}

/// Enumerate the reduced words of length <= 3, find every pair with the same image, and report
/// the resulting kernel elements (each of length <= 6).
///
/// `parent[i]` is the index of the word obtained from `words[i]` by deleting its last letter
/// (a prefix of a reduced word is reduced, so it is again in the list), and `lastgen[i]` is
/// that last letter.  Images are therefore built with one matrix product per word.
fn census(
    a: &[i64],
    words: &[Vec<usize>],
    parent: &[u32],
    lastgen: &[u32],
    mats: &mut Vec<i128>,
    order: &mut Vec<u32>,
) -> Vec<Finding> {
    let rep = Rep::new(a);
    let d = rep.dim;
    let sz = d * d;
    let nw = words.len();

    mats.clear();
    mats.resize(nw * sz, 0);
    // words[0] is the empty word
    for r in 0..d {
        mats[r * d + r] = 1;
    }
    let mut tmp = vec![0i128; sz];
    for idx in 1..nw {
        let p = parent[idx] as usize;
        let g = lastgen[idx] as usize;
        {
            let (lo, hi) = mats.split_at_mut(idx * sz);
            let src = &lo[p * sz..p * sz + sz];
            rep.mul(src, &rep.gens[g], &mut tmp);
            hi[0..sz].copy_from_slice(&tmp);
        }
        rep.normalize(&mut mats[idx * sz..idx * sz + sz]);
    }

    let m: &[i128] = &mats[..];
    order.clear();
    order.extend(0..nw as u32);
    order.sort_unstable_by(|&i, &j| {
        let si = &m[i as usize * sz..(i as usize + 1) * sz];
        let sj = &m[j as usize * sz..(j as usize + 1) * sz];
        si.cmp(sj)
    });

    let mut out: Vec<Finding> = Vec::new();
    let mut i = 0usize;
    while i < nw {
        let mut k = i + 1;
        while k < nw {
            let si = &m[order[i] as usize * sz..(order[i] as usize + 1) * sz];
            let sk = &m[order[k] as usize * sz..(order[k] as usize + 1) * sz];
            if si != sk {
                break;
            }
            k += 1;
        }
        if k - i >= 2 {
            for p in i..k {
                for q in (p + 1)..k {
                    let u = &words[order[p] as usize];
                    let v = &words[order[q] as usize];
                    let mut cand: Vec<usize> = u.clone();
                    cand.extend(v.iter().rev());
                    let r = reduce(&cand);
                    if !r.is_empty() {
                        out.push(Finding {
                            len: r.len(),
                            supp: support(&r).len(),
                            word: r,
                        });
                    }
                }
            }
        }
        i = k;
    }
    out
}

// ---------------------------------------------------------------- statistics of a leg tuple

fn e_stat(a: &[i64]) -> usize {
    let n = a.len();
    let mut e = 0;
    // positions i in {1, n-1} (1-indexed legs): a_i = a_{i+1}
    let mut ps: Vec<usize> = vec![1, n - 1];
    ps.sort_unstable();
    ps.dedup();
    for i in ps {
        if a[i - 1] == a[i] {
            e += 1;
        }
    }
    e
}

fn t_stat(a: &[i64]) -> usize {
    let n = a.len();
    let mut t = 0;
    for i in 1..=(n.saturating_sub(2)) {
        if a[i - 1] == a[i] && a[i] == a[i + 1] {
            t += 1;
        }
    }
    t
}

// ---------------------------------------------------------------- driver

fn all_reduced_words(n: usize, maxlen: usize) -> (Vec<Vec<usize>>, Vec<u32>, Vec<u32>) {
    let mut out: Vec<Vec<usize>> = vec![vec![]];
    let mut parent: Vec<u32> = vec![0];
    let mut lastgen: Vec<u32> = vec![0];
    let mut frontier: Vec<u32> = vec![0];
    for _ in 0..maxlen {
        let mut next: Vec<u32> = Vec::new();
        for &pi in frontier.iter() {
            for g in 0..=n {
                let mut c = out[pi as usize].clone();
                c.push(g);
                if reduce(&c).len() == c.len() {
                    out.push(c);
                    parent.push(pi);
                    lastgen.push(g as u32);
                    next.push((out.len() - 1) as u32);
                }
            }
        }
        frontier = next;
    }
    (out, parent, lastgen)
}

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 3 {
        eprintln!("usage: ortho_len6 <n> <L> [--quiet]");
        std::process::exit(2);
    }
    let n: usize = args[1].parse().unwrap();
    let l: i64 = args[2].parse().unwrap();
    let quiet = args.iter().any(|s| s == "--quiet");
    assert!(n >= 2, "n >= 2");

    let (words, parent, lastgen) = all_reduced_words(n, 3);
    let mut mats: Vec<i128> = Vec::new();
    let mut order: Vec<u32> = Vec::new();
    println!(
        "# n = {}, legs in 1..{} (primitive tuples only), reduced words of length <= 3: {}",
        n,
        l,
        words.len()
    );

    // counters
    let mut n_tuples: u64 = 0;
    let mut n_with_short_kernel: u64 = 0;
    let mut n_len6_supp2: u64 = 0;
    let mut violations_len6_supp3: u64 = 0;
    let mut violations_short: u64 = 0; // kernel element of length < 6
    // (e,t) class -> number of tuples, number of those with a length-6 kernel element
    let mut cls: std::collections::BTreeMap<(usize, usize), (u64, u64)> =
        std::collections::BTreeMap::new();

    let mut a = vec![1i64; n];
    let total: u64 = (l as u64).pow(n as u32);
    let mut counter: u64 = 0;
    loop {
        // primitive tuples only: rho_{lambda a} = rho_a up to conjugation by a dilation
        let mut g = 0i64;
        for &x in a.iter() {
            g = gcd64(g, x);
        }
        if g == 1 {
            n_tuples += 1;
            let e = e_stat(&a);
            let t = t_stat(&a);
            let f = census(&a, &words, &parent, &lastgen, &mut mats, &mut order);
            let mut saw6 = false;
            for fd in f.iter() {
                if fd.len < 6 {
                    violations_short += 1;
                    println!(
                        "VIOLATION (length {} < 6): n={} a={:?} word={:?} supp={}",
                        fd.len, n, a, fd.word, fd.supp
                    );
                } else if fd.len == 6 {
                    saw6 = true;
                    if fd.supp >= 3 {
                        violations_len6_supp3 += 1;
                        println!(
                            "VIOLATION (length 6, support {} >= 3): n={} a={:?} word={:?}",
                            fd.supp, n, a, fd.word
                        );
                    } else {
                        n_len6_supp2 += 1;
                        if !is_rank_two_hexagon(&fd.word) {
                            println!(
                                "NOTE (length 6, support 2, not (R_i R_{{i+1}})^3): n={} a={:?} word={:?}",
                                n, a, fd.word
                            );
                        }
                    }
                }
            }
            if !f.is_empty() {
                n_with_short_kernel += 1;
            }
            let ent = cls.entry((e, t)).or_insert((0, 0));
            ent.0 += 1;
            if saw6 {
                ent.1 += 1;
            }
            // the decisive consistency check: a length-6 kernel element exists iff t >= 1
            if saw6 != (t >= 1) {
                println!(
                    "MISMATCH with (e,t) rule: n={} a={:?} e={} t={} saw_length6={}",
                    n, a, e, t, saw6
                );
            }
        }
        counter += 1;
        if !quiet && counter % 500_000 == 0 {
            eprintln!("  ... {} / {} tuples scanned", counter, total);
        }
        // odometer
        let mut i = 0;
        loop {
            if i == n {
                // done
                println!("# scanned {} primitive tuples out of {} in the box", n_tuples, total);
                println!("# tuples with a nontrivial kernel element of length <= 6 : {}", n_with_short_kernel);
                println!("# length-6 kernel elements found inside a rank-two parabolic (support 2) : {}", n_len6_supp2);
                println!("# VIOLATIONS, kernel element of length < 6                : {}", violations_short);
                println!("# VIOLATIONS, kernel element of length 6 with support >= 3: {}", violations_len6_supp3);
                println!("# (e,t) class table: (e,t) -> tuples, of which have a length-6 kernel element");
                for ((e, t), (c, c6)) in cls.iter() {
                    println!("#   (e={},t={}) -> {:>10} tuples, {:>10} with length-6 kernel element", e, t, c, c6);
                }
                let verdict = if violations_short == 0 && violations_len6_supp3 == 0 {
                    "PASS: every kernel element of length 6 lies in a rank-two standard parabolic"
                } else {
                    "FAIL"
                };
                println!("# {}", verdict);
                return;
            }
            a[i] += 1;
            if a[i] <= l {
                break;
            }
            a[i] = 1;
            i += 1;
        }
    }
}
