#!/usr/bin/env python3
"""Arithmetic preconditions for a tree ping-pong on the orthoscheme point group.

A single faithful leg tuple settles the generic form of the faithfulness problem, and by the
necessary condition it is enough that the POINT GROUP be faithful there.  The point group is a
subgroup of O_3(Q) generated by the four facet reflections, so it lies in O_3(Z[1/N]) where N is
the product of the primes dividing |m_1|^2 = a_1^2 + a_2^2 and |m_2|^2 = a_2^2 + a_3^2.

For a Bass-Serre argument one wants ONE prime: SO_3 acts on the Bruhat-Tits building over Q_p,
which is a tree exactly when the form is isotropic over Q_p, and a group acting on a single tree
is covered by Bass-Serre theory while a group acting on a product of two trees is not.

    usage:  pingpong_setup.py [legs] [primes]
    e.g.    pingpong_setup.py 1,2,11 5      one prime, acts on ONE tree
            pingpong_setup.py 1,2,3 5,13    two primes, product of trees, no Bass-Serre
"""
from fractions import Fraction as F
import sys

def vp(x, p):
    if x == 0: return None
    n, d = x.numerator, x.denominator; v = 0
    while n % p == 0: n //= p; v += 1
    while d % p == 0: d //= p; v -= 1
    return v

def lin_refl(m, n):
    d = sum(x * x for x in m)
    return tuple(tuple((F(1) if i == j else F(0)) - 2 * m[i] * m[j] / d for j in range(n))
                 for i in range(n))

def normals(a):
    n = len(a); M = []
    v = [F(0)] * n; v[0] = F(1); M.append(tuple(v))
    for j in range(1, n):
        v = [F(0)] * n; v[j - 1] = F(a[j]); v[j] = F(-a[j - 1]); M.append(tuple(v))
    v = [F(0)] * n; v[n - 1] = F(1); M.append(tuple(v))
    return M

a = [int(x) for x in (sys.argv[1] if len(sys.argv) > 1 else "1,2,11").split(',')]
primes = [int(x) for x in (sys.argv[2] if len(sys.argv) > 2 else "5").split(',')]
n = len(a)
G = [lin_refl(m, n) for m in normals(a)]

print(f"legs {tuple(a)}   |m_1|^2 = {a[0]**2 + a[1]**2}   |m_{n-1}|^2 = {a[n-2]**2 + a[n-1]**2}")
for p in primes:
    print(f"--- valuation at p = {p} ---")
    for k, g in enumerate(G):
        vs = [vp(x, p) for row in g for x in row if x != 0]
        print(f"  R_{k}: min valuation {min(vs):>3}   {'integral' if min(vs) >= 0 else 'NOT integral'}")
    sq = {(i * i) % p for i in range(p)}
    hit = next(((x, y, z) for x in range(p) for y in range(p) for z in range(p)
                if (x, y, z) != (0, 0, 0) and (x * x + y * y + z * z) % p == 0), None)
    print(f"  x^2+y^2+z^2 isotropic mod {p}: {hit is not None}"
          f"{'  e.g. ' + str(hit) if hit else ''}"
          f"  -> SO_3 {'split, building is a TREE' if hit else 'anisotropic, building is a POINT'}")

def mul(A, B): return tuple(tuple(sum(A[i][k] * B[k][j] for k in range(n)) for j in range(n))
                            for i in range(n))
def tr(A): return tuple(tuple(A[j][i] for j in range(n)) for i in range(n))
I = tuple(tuple(F(1) if i == j else F(0) for j in range(n)) for i in range(n))
print("all generators orthogonal:", all(mul(tr(g), g) == I for g in G))
