from fractions import Fraction as F
import itertools
def refl(v):
    n=4; d=sum(x*x for x in v)
    return tuple(tuple((F(1) if i==j else F(0))-2*v[i]*v[j]/d for j in range(n)) for i in range(n))
def diag(*d): return tuple(tuple(F(d[i]) if i==j else F(0) for j in range(4)) for i in range(4))
def mul(A,B): return tuple(tuple(sum(A[i][k]*B[k][j] for k in range(4)) for j in range(4)) for i in range(4))
I4=diag(1,1,1,1)
R0=diag(-1,1,1,1); R4=diag(1,1,-1,1)
R1=refl((F(3),F(4),F(0),F(0))); R3=refl((F(0),F(0),F(5),F(12))); R2=refl((F(0),F(8),F(0),F(15)))
def vpmin(M,p):
    def vp(x):
        if x==0: return 10**9
        n,d=x.numerator,x.denominator; v=0
        while n%p==0: n//=p; v+=1
        while d%p==0: d//=p; v-=1
        return v
    return min(vp(M[i][j]) for i in range(4) for j in range(4))
# C = <R0,R4>, order 4 ; A = <R0,R2,R4>, order 8 ; B\C generated by R1,R3 over C
C=[I4,R0,R4,mul(R0,R4)]
A=set()
for a in itertools.product([I4,R0],[I4,R2],[I4,R4]):
    A.add(mul(mul(a[0],a[1]),a[2]))
A=list(A)
AminusC=[g for g in A if g not in C]
print(f"|C| = {len(C)},  |A| = {len(A)},  |A\\C| = {len(AminusC)}")
print()
print("PING-PONG TEST: does every element of A\\C move the 17-adic lattice,")
print("and does every nontrivial element of B\\C move the 5- or 13-adic one?")
print()
print("A\\C, minimum valuations (want NEGATIVE at 17, ZERO at 5 and 13):")
ok=True
for g in AminusC:
    v5,v13,v17=vpmin(g,5),vpmin(g,13),vpmin(g,17)
    good = (v17<0 and v5>=0 and v13>=0)
    ok &= good
    print(f"   v5={v5:3d} v13={v13:3d} v17={v17:3d}  {'OK' if good else 'FAILS'}")
print("   ALL of A\\C move only the 17-adic place" if ok else "   NOT uniform")
print()
print("B\\C samples (words in R1,R3 over C), want v17 = 0 and (v5<0 or v13<0):")
B0=[R1,R3,mul(R1,R3),mul(R3,R1),mul(R1,mul(R3,R1)),mul(R3,mul(R1,R3)),mul(mul(R1,R3),mul(R1,R3))]
ok2=True
for g in B0:
    for c in C:
        h=mul(g,c)
        v5,v13,v17=vpmin(h,5),vpmin(h,13),vpmin(h,17)
        good=(v17>=0 and (v5<0 or v13<0))
        ok2 &= good
    v5,v13,v17=vpmin(g,5),vpmin(g,13),vpmin(g,17)
    print(f"   v5={v5:3d} v13={v13:3d} v17={v17:3d}")
print("   ALL sampled B\\C fix the 17-adic place and move 5 or 13" if ok2 else "   NOT uniform")
