

# This file was *autogenerated* from the file mordell_32a2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_60 = Integer(60); _sage_const_61 = Integer(61)#!/usr/bin/env sage
# Verifies the V_{1/2} branch. V_{1/2}: a^4 + 6 a^2 c^2 + c^4 = k^2 is the
# square-discriminant condition for cos^2(theta) = 1/2. Jacobian is Cremona 32a2.
E = EllipticCurve([_sage_const_0 , _sage_const_0 , _sage_const_0 , -_sage_const_1 , _sage_const_0 ])       # y^2 = x^3 - x
print("V_{1/2} curve y^2 = x^3 - x")
print("  Cremona label :", E.cremona_label())     # 32a2  (NOT 'E_6')
print("  conductor     :", E.conductor())          # 32
print("  rank          :", E.rank())               # 0
print("  torsion       :", E.torsion_subgroup().invariants())  # (2,2): (0,0),(+-1,0),oo
R = QQ['t']; (t,) = R._first_ngens(1); f = t**_sage_const_4  + _sage_const_6 *t**_sage_const_2  + _sage_const_1 
sols = sorted({QQ(n)/d for n in range(-_sage_const_60 ,_sage_const_61 ) for d in range(_sage_const_1 ,_sage_const_61 )
               if f(QQ(n)/d) >= _sage_const_0  and f(QQ(n)/d).is_square()})
print("  rational t=a/c with f(t) square:", sols, "(only t=0)")
assert E.rank() == _sage_const_0  and sols == [_sage_const_0 ]
print("  => no distinct-positive-rational legs realize cos^2 theta = 1/2. OK")

