

# This file was *autogenerated* from the file mordell_24a1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_28 = Integer(28); _sage_const_192 = Integer(192); _sage_const_4 = Integer(4); _sage_const_14 = Integer(14); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_60 = Integer(60); _sage_const_61 = Integer(61)#!/usr/bin/env sage
# Verifies the V_{1/4} branch of Class C faithfulness (paper Thm. master-C-uncond).
# V_{1/4}: a^4 + 14 a^2 c^2 + c^4 = m^2  is the square-discriminant condition for
# cos^2(theta) = 1/4 (interior dihedral). Its Jacobian is Cremona 24a1.
E = EllipticCurve([_sage_const_0 , -_sage_const_28 , _sage_const_0 , _sage_const_192 , _sage_const_0 ])    # y^2 = x(x-12)(x-16)
print("V_{1/4} curve y^2 = x(x-12)(x-16)")
print("  Cremona label :", E.cremona_label())     # 24a1
print("  conductor     :", E.conductor())          # 24
print("  rank          :", E.rank())               # 0
print("  torsion       :", E.torsion_subgroup().invariants())  # (2,4)
# Rational points t=a/c with a^4+14 a^2 c^2 + c^4 a perfect square:
R = QQ['t']; (t,) = R._first_ngens(1); f = t**_sage_const_4  + _sage_const_14 *t**_sage_const_2  + _sage_const_1 
sols = sorted({QQ(n)/d for n in range(-_sage_const_60 ,_sage_const_61 ) for d in range(_sage_const_1 ,_sage_const_61 )
               if f(QQ(n)/d) >= _sage_const_0  and f(QQ(n)/d).is_square()})
print("  rational t=a/c with f(t) square:", sols, "(all give ac=0 or a=+-c)")
assert E.rank() == _sage_const_0  and sols == [-_sage_const_1 , _sage_const_0 , _sage_const_1 ]
print("  => no distinct-positive-rational legs realize cos^2 theta = 1/4. OK")

