

# This file was *autogenerated* from the file mordell_72a2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1500 = Integer(1500); _sage_const_360000 = Integer(360000); _sage_const_9 = Integer(9); _sage_const_4 = Integer(4); _sage_const_30 = Integer(30); _sage_const_2 = Integer(2); _sage_const_60 = Integer(60); _sage_const_61 = Integer(61); _sage_const_1 = Integer(1)#!/usr/bin/env sage
# Verifies the V_{3/4} branch. V_{3/4}: 9 a^4 + 30 a^2 c^2 + 9 c^4 = k^2 is the
# square-discriminant condition for cos^2(theta) = 3/4. Jacobian is Cremona 72a2.
E = EllipticCurve([_sage_const_0 , -_sage_const_1500 , _sage_const_0 , _sage_const_360000 , _sage_const_0 ])   # y^2 = x(x-300)(x-1200)
print("V_{3/4} curve y^2 = x(x-300)(x-1200)")
print("  Cremona label :", E.cremona_label())     # 72a2
print("  conductor     :", E.conductor())          # 72
print("  rank          :", E.rank())               # 0
print("  torsion       :", E.torsion_subgroup().invariants())  # (2,2)
R = QQ['t']; (t,) = R._first_ngens(1); f = _sage_const_9 *t**_sage_const_4  + _sage_const_30 *t**_sage_const_2  + _sage_const_9 
sols = sorted({QQ(n)/d for n in range(-_sage_const_60 ,_sage_const_61 ) for d in range(_sage_const_1 ,_sage_const_61 )
               if f(QQ(n)/d) >= _sage_const_0  and f(QQ(n)/d).is_square()})
print("  rational t=a/c with f(t) square:", sols, "(only t=0)")
assert E.rank() == _sage_const_0  and sols == [_sage_const_0 ]
print("  => no distinct-positive-rational legs realize cos^2 theta = 3/4. OK")

