/-
The Coxeter reference group of a stratum, as a free product, and the statement
that exactly one of the rotation relations already holds in it
(paper 4, Theorem "Rotation relations", part (iii)).

The Coxeter presentation of `W_m` imposes no relation involving `x_2` beyond
`x_2^2`, so

    W_m  =  D_m * C_2,

a free product.  Part (iii) of the theorem says that among the `c^2` words
`w_{a,b}` exactly one, `r_2 (r_0 r_1)^c r_2`, has finite order in `W_m`; the
paper proves this with the torsion theorem for free products (an element of
finite order is conjugate into a factor) followed by a cyclic reduction.

Mathlib supplies the free product `Monoid.CoprodI`, its normal form
`Monoid.CoprodI.Word.equiv`, and `DihedralGroup`.  It does **not** supply the
torsion theorem, so that step has to be built here, and the route is the normal
form: an element is trivial exactly when its normal form is empty, and the
cyclic reduction of `u₀ x₂ u₁ x₂ u₂` is `u₂u₀ x₂ u₁ x₂`, which has two
syllables from `D_m` unless `u₂ = u₀⁻¹`.

This file pins the statement.  The proof is not written.
-/
import Mathlib.GroupTheory.CoprodI
import Mathlib.GroupTheory.SpecificGroups.Dihedral

namespace CoxeterTorsion

open Monoid

/-- The orders of the two factors: the apex dihedral group `D_m`, and the
group of order two generated by the third reflection (`D_1 ≅ C_2`). -/
def deg (m : ℕ) : Fin 2 → ℕ
  | 0 => m
  | 1 => 1

/-- The two factors of the free product. -/
abbrev factor (m : ℕ) (i : Fin 2) := DihedralGroup (deg m i)

/-- `W m = D_m * C_2`, the Coxeter reference group of the stratum. -/
abbrev W (m : ℕ) := CoprodI (factor m)

/-- The apex rotation `r_0 r_1`. -/
def s (m : ℕ) : W m := CoprodI.of (i := 0) (DihedralGroup.r 1)

/-- The third reflection `r_2`. -/
def t (m : ℕ) : W m := CoprodI.of (i := 1) (DihedralGroup.sr 0)

/-- `r_2` is an involution. -/
theorem t_sq (m : ℕ) : t m * t m = 1 := by
  rw [t, ← map_mul]
  simp

/-- The apex rotation has order dividing `m`. -/
theorem s_pow (m : ℕ) : s m ^ m = 1 := by
  rw [s, ← map_pow]
  simp

/-- The apex rotation by `k` steps, as an element of `W m`. -/
def rot (m : ℕ) (k : ZMod m) : W m :=
  CoprodI.of (i := 0) (show factor m 0 from DihedralGroup.r k)

/-- The element the paper calls `w_{a,b}` once its blocks are read off:
`u₀ x₂ u₁ x₂ u₂`, with each `u` in the dihedral factor. -/
def blockWord (m : ℕ) (u₀ u₁ u₂ : factor m 0) : W m :=
  CoprodI.of (i := 0) u₀ * t m * CoprodI.of (i := 0) u₁ * t m * CoprodI.of (i := 0) u₂

/-- **Easy direction of part (iii).**  If the outer blocks cancel, the word is a
conjugate of `u₁`, which lives in the finite factor `D_m`, so it has finite
order.  This is the relation `r_2 (r_0 r_1)^c r_2` of the paper. -/
theorem finite_order_of_cancel (m : ℕ) (hm : 0 < m) (u₀ u₁ u₂ : factor m 0)
    (h : u₂ * u₀ = 1) : IsOfFinOrder (blockWord m u₀ u₁ u₂) := by
  haveI : NeZero (deg m 0) := ⟨hm.ne'⟩
  have ht : (t m)⁻¹ = t m := inv_eq_of_mul_eq_one_right (t_sq m)
  have hu : u₂ = u₀⁻¹ := eq_inv_of_mul_eq_one_left h
  have hc : blockWord m u₀ u₁ u₂
      = (CoprodI.of (i := 0) u₀ * t m) * CoprodI.of (i := 0) u₁ *
        (CoprodI.of (i := 0) u₀ * t m)⁻¹ := by
    simp only [blockWord, hu, mul_inv_rev, ht, map_inv]
    group
  obtain ⟨n, hn, hpow⟩ := (isOfFinOrder_of_finite u₁).exists_pow_eq_one
  refine isOfFinOrder_iff_pow_eq_one.mpr ⟨n, hn, ?_⟩
  rw [hc]
  have hconj : ∀ (c y : W m), (c * y * c⁻¹) ^ n = c * y ^ n * c⁻¹ := by
    intro c y
    simp
  rw [hconj, ← map_pow, hpow, map_one, mul_one, mul_inv_cancel]

/-- Conjugation preserves finite order. -/
theorem isOfFinOrder_conj {G : Type*} [Group G] (c x : G) (hx : IsOfFinOrder x) :
    IsOfFinOrder (c * x * c⁻¹) := by
  obtain ⟨n, hn, hp⟩ := hx.exists_pow_eq_one
  refine isOfFinOrder_iff_pow_eq_one.mpr ⟨n, hn, ?_⟩
  have hconj : (c * x * c⁻¹) ^ n = c * x ^ n * c⁻¹ := by
    simp
  rw [hconj, hp, mul_one, mul_inv_cancel]

/-- A nonempty reduced word is never the identity.  `Word.prod` is injective
because it is the inverse half of the normal-form equivalence `Word.equiv`, and
`Word.prod empty = 1`, so a word with a nonempty letter list cannot be `1`. -/
theorem neword_prod_ne_one {m : ℕ} {i j : Fin 2}
    (w : CoprodI.NeWord (factor m) i j) : w.prod ≠ 1 := by
  intro hw
  have h1 : CoprodI.Word.equiv.symm w.toWord
      = CoprodI.Word.equiv.symm (CoprodI.Word.empty) := by
    show CoprodI.Word.prod w.toWord = CoprodI.Word.prod CoprodI.Word.empty
    rw [CoprodI.Word.prod_empty]
    exact hw
  have h2 : w.toWord = CoprodI.Word.empty := CoprodI.Word.equiv.symm.injective h1
  exact CoprodI.NeWord.toList_ne_nil w (congrArg CoprodI.Word.toList h2)

/-- The third reflection, as an element of the second factor. -/
def tt (m : ℕ) : factor m 1 := DihedralGroup.sr 0

theorem tt_ne_one (m : ℕ) : tt m ≠ 1 := by
  simp only [tt, DihedralGroup.one_def, ne_eq, reduceCtorEq, not_false_eq_true]

/-- The alternating block `x₂ · u₁ · x₂ · v`, as a reduced word.  Its letters
alternate between the two factors, so it is reduced by construction. -/
def blk (m : ℕ) (u₁ v : factor m 0) (h₁ : u₁ ≠ 1) (hv : v ≠ 1) :
    CoprodI.NeWord (factor m) 1 0 :=
  .append (.append (.singleton (tt m) (tt_ne_one m)) (by decide) (.singleton u₁ h₁))
    (by decide)
    (.append (.singleton (tt m) (tt_ne_one m)) (by decide) (.singleton v hv))

theorem blk_prod (m : ℕ) (u₁ v : factor m 0) (h₁ : u₁ ≠ 1) (hv : v ≠ 1) :
    (blk m u₁ v h₁ hv).prod
      = t m * CoprodI.of (i := 0) u₁ * (t m * CoprodI.of (i := 0) v) := by
  simp only [blk, CoprodI.NeWord.append_prod, CoprodI.NeWord.prod_singleton, tt, t]

/-- `blk` concatenated with itself `n+1` times: still alternating, still reduced,
because the last letter lies in factor `0` and the first in factor `1`. -/
def blkPow (m : ℕ) (u₁ v : factor m 0) (h₁ : u₁ ≠ 1) (hv : v ≠ 1) :
    ℕ → CoprodI.NeWord (factor m) 1 0
  | 0 => blk m u₁ v h₁ hv
  | (n + 1) => .append (blk m u₁ v h₁ hv) (by decide) (blkPow m u₁ v h₁ hv n)

theorem blkPow_prod (m : ℕ) (u₁ v : factor m 0) (h₁ : u₁ ≠ 1) (hv : v ≠ 1) (n : ℕ) :
    (blkPow m u₁ v h₁ hv n).prod = (blk m u₁ v h₁ hv).prod ^ (n + 1) := by
  induction n with
  | zero => simp [blkPow]
  | succ k ih =>
      rw [blkPow, CoprodI.NeWord.append_prod, ih]
      rw [← pow_succ']

/-- The alternating word `x₂ u₁ x₂ v` has infinite order: every power is a
nonempty reduced word, hence nontrivial. -/
theorem blk_prod_infinite_order (m : ℕ) (u₁ v : factor m 0) (h₁ : u₁ ≠ 1) (hv : v ≠ 1) :
    ¬ IsOfFinOrder (blk m u₁ v h₁ hv).prod := by
  intro hfin
  obtain ⟨n, hn, hpow⟩ := hfin.exists_pow_eq_one
  obtain ⟨k, rfl⟩ : ∃ k, n = k + 1 := ⟨n - 1, by omega⟩
  exact neword_prod_ne_one (blkPow m u₁ v h₁ hv k) (by rw [blkPow_prod]; exact hpow)

/-- **Hard direction of part (iii).**  If the outer blocks do not cancel, the
word is conjugate to the cyclically reduced `x₂ u₁ x₂ (u₂u₀)`, which alternates
between the two factors, so it has infinite order. -/
theorem infinite_order_of_noncancel (m : ℕ)
    (u₀ u₁ u₂ : factor m 0) (hu₁ : u₁ ≠ 1) (h : u₂ * u₀ ≠ 1) :
    ¬ IsOfFinOrder (blockWord m u₀ u₁ u₂) := by
  intro hfin
  have key : (CoprodI.of (i := 0) u₀)⁻¹ * blockWord m u₀ u₁ u₂ * CoprodI.of (i := 0) u₀
      = (blk m u₁ (u₂ * u₀) hu₁ h).prod := by
    rw [blk_prod]
    simp only [blockWord, map_mul]
    group
  have h2 := isOfFinOrder_conj (CoprodI.of (i := 0) u₀)⁻¹ (blockWord m u₀ u₁ u₂) hfin
  rw [inv_inv, key] at h2
  exact blk_prod_infinite_order m u₁ (u₂ * u₀) hu₁ h h2

/-- **Part (iii), assembled.**  Among the words of the rotation family the only
one of finite order in `W m` is the one whose outer blocks cancel, namely the
conjugate `r_2 (r_0 r_1)^c r_2`. -/
theorem finite_order_iff (m : ℕ) (hm : 0 < m)
    (u₀ u₁ u₂ : factor m 0) (hu₁ : u₁ ≠ 1) :
    IsOfFinOrder (blockWord m u₀ u₁ u₂) ↔ u₂ * u₀ = 1 := by
  constructor
  · intro hfin
    by_contra hne
    exact infinite_order_of_noncancel m u₀ u₁ u₂ hu₁ hne hfin
  · exact finite_order_of_cancel m hm u₀ u₁ u₂

end CoxeterTorsion
