// BFS of the group generated by five reflections in O(4) over F_p, for the
// compact-form configuration of W_4, compared against the RACG growth series.
// Memory guard is INSIDE the tool (Rule 8): the frontier is stored flat and a
// forward projection refuses to expand a level that would exceed the budget.
use std::collections::HashSet;

const N: usize = 4;
type M = [u64; 16];

fn pw(mut b: u64, mut e: u64, p: u64) -> u64 {
    let mut r = 1u64; b %= p;
    while e > 0 { if e & 1 == 1 { r = (r as u128 * b as u128 % p as u128) as u64; }
        b = (b as u128 * b as u128 % p as u128) as u64; e >>= 1; }
    r
}
fn inv(a: u64, p: u64) -> u64 { pw(a, p - 2, p) }
fn mul(a: &M, b: &M, p: u64) -> M {
    let mut c = [0u64; 16];
    for i in 0..N { for k in 0..N { if a[i*N+k] == 0 { continue; }
        let aik = a[i*N+k] as u128;
        for j in 0..N { c[i*N+j] = ((c[i*N+j] as u128 + aik * b[k*N+j] as u128) % p as u128) as u64; } } }
    c
}
/// reflection with normal v (mod p): I - 2 v v^T / <v,v>
fn refl(v: &[u64; 4], p: u64) -> M {
    let mut d = 0u128;
    for i in 0..N { d = (d + (v[i] as u128 * v[i] as u128)) % p as u128; }
    let di = inv(d as u64, p);
    let mut m = [0u64; 16];
    for i in 0..N { for j in 0..N {
        let t = (2u128 * v[i] as u128 % p as u128 * v[j] as u128 % p as u128 * di as u128) % p as u128;
        let e = if i == j { 1u128 } else { 0u128 };
        m[i*N+j] = ((e + p as u128 - t) % p as u128) as u64;
    } }
    m
}
fn projected_bytes(front: usize, ball: usize) -> u64 {
    (front as u64) * (16 * 8) + (ball as u64) * 40
}
fn main() {
    let a: Vec<String> = std::env::args().collect();
    let p: u64 = a[1].parse().unwrap();
    let depth: usize = a[2].parse().unwrap();
    let budget_mb: u64 = if a.len() > 3 { a[3].parse().unwrap() } else { 2000 };
    // compact-form configuration: v0=e1; v1 in <e1,e2>; v3,v4 in <e3,e4>; v2 in <e2,w>, w = v4-perp
    // parameters chosen as rational points of the 3-dim moduli, generic mod p
    let (c1, s1) = (3u64, 4u64);         // v1 = (3,4,0,0)/5
    let (c4, s4) = (5u64, 12u64);        // v4 = (0,0,5,12)/13
    let (c3, s3) = (8u64, 15u64);        // v3 = (0,0,8,15)/17
    let (e2, ew) = (7u64, 20u64);        // v2 = e2*e2 + ew*w,  w = (0,0,-12,5)/13 perp to v4
    let v0 = [1, 0, 0, 0];
    let v1 = [c1, s1, 0, 0];
    let v3 = [0, 0, c3, s3];
    let v4 = [0, 0, c4, s4];
    let w = [0u64, 0, (p - s4) % p, c4];
    let v2 = [0, e2, (ew as u128 * w[2] as u128 % p as u128) as u64,
                     (ew as u128 * w[3] as u128 % p as u128) as u64];
    let gens: Vec<M> = vec![refl(&v0,p), refl(&v1,p), refl(&v2,p), refl(&v3,p), refl(&v4,p)];
    // relation audit: R_i R_j = R_j R_i must hold exactly for |i-j|>=2 and fail otherwise
    for i in 0..5 { for j in (i+1)..5 {
        let ij = mul(&gens[i], &gens[j], p); let ji = mul(&gens[j], &gens[i], p);
        let comm = ij == ji; let want = (j - i) >= 2;
        if comm != want { println!("RELATION FAILURE at ({},{}) commutes={} expected={}", i, j, comm, want); }
    } }
    println!("relations verified mod {}", p);
    let id: M = { let mut m = [0u64;16]; for i in 0..N { m[i*N+i] = 1; } m };
    let mut seen: HashSet<M> = HashSet::new();
    seen.insert(id);
    let mut front: Vec<M> = vec![id];
    println!("  d  |sphere|   |ball|");
    println!("  0         1        1");
    for d in 1..=depth {
        let proj = projected_bytes(front.len() * 5, seen.len() + front.len() * 5);
        if proj > budget_mb * 1_000_000 {
            println!("  refusing depth {}: projection {} MB exceeds budget {} MB", d, proj/1_000_000, budget_mb);
            break;
        }
        let mut next: Vec<M> = Vec::new();
        for x in &front { for g in &gens {
            let y = mul(x, g, p);
            if seen.insert(y) { next.push(y); }
        } }
        println!("{:3} {:9} {:8}", d, next.len(), seen.len());
        if next.is_empty() { break; }
        front = next;
    }
}
