#!/usr/bin/env python3
"""
G39 -- Direct non-commutative computation of I_A cap I_B as a LEFT Z[Q]-module.

Q = D_inf x Z/2 = <X, Y, c | X^2, Y^2, c^2, cX=Xc, cY=Yc>.
D_inf = <X, Y | X^2, Y^2> is NON-abelian; XY has infinite order.

Normal form for each q in Q: alternating reduced word in {X, Y} (possibly empty),
times c^{0 or 1}.  So each q is encoded as (word: str over {'X','Y'} alternating
with no two equal consecutive letters, eps in {0,1}).

I_A = left ideal generated by {X-1, X'-1} where X' = cX.
    => Equivalent left generators: {X-1, cX-1}.  But cX-1 = c(X-1) + (c-1).
    So as a LEFT ideal, I_A = Z[Q].(X-1) + Z[Q].(c-1).
I_B = left ideal generated by {Y-1}.

We truncate Z[Q] to words of length <= L (in {X,Y}), with eps in {0,1}.
Number of group elements: 2 * (2L + 1)  (empty + 2 words of each length k = 1..L,
namely starting-with-X or starting-with-Y) times 2 for c.

Inside this finite-dim Z-module, we compute:
  - V_A   = Z-span of all q * (X-1) and q * (c-1) for |q| small enough that
            the product lies in the truncation.
  - V_B   = Z-span of all q * (Y-1).
  - V_A cap V_B in the truncation.

Then we ask: as a LEFT Z[Q]-module, how many generators does V_A cap V_B need?

Note: working over Z, the intersection is a Z-lattice.  Computing it requires
HNF / Smith normal form on integer matrices.
"""
from __future__ import annotations

import sys
from itertools import product as iproduct
from typing import Dict, List, Tuple

# -----------------------------------------------------------------------------
# Word machinery for D_inf
# -----------------------------------------------------------------------------
# A reduced word in D_inf is a string in {'X','Y'} with no two consecutive
# letters equal.  Multiplication: concatenate, then cancel adjacent equal
# letters (each cancellation removes the equal pair because X^2 = Y^2 = 1).

def reduce_word(w: str) -> str:
    out: List[str] = []
    for ch in w:
        if out and out[-1] == ch:
            out.pop()
        else:
            out.append(ch)
    return "".join(out)


def mult_word(u: str, v: str) -> str:
    return reduce_word(u + v)


# Q element = (word, eps).  c is central, c^2 = 1.
QElt = Tuple[str, int]


def q_mult(a: QElt, b: QElt) -> QElt:
    w1, e1 = a
    w2, e2 = b
    return (mult_word(w1, w2), (e1 + e2) % 2)


def q_id() -> QElt:
    return ("", 0)


# Enumerate all reduced words of length <= L
def enum_words(L: int) -> List[str]:
    out = [""]
    # Words starting with X: X, XY, XYX, XYXY, ...
    # Words starting with Y: Y, YX, YXY, YXYX, ...
    for k in range(1, L + 1):
        wX = "".join(["X" if i % 2 == 0 else "Y" for i in range(k)])
        wY = "".join(["Y" if i % 2 == 0 else "X" for i in range(k)])
        out.append(wX)
        out.append(wY)
    return out


def enum_Q(L: int) -> List[QElt]:
    return [(w, e) for w in enum_words(L) for e in (0, 1)]


# -----------------------------------------------------------------------------
# Z[Q] elements as dicts QElt -> int
# -----------------------------------------------------------------------------

ZQ = Dict[QElt, int]


def zq_zero() -> ZQ:
    return {}


def zq_add(a: ZQ, b: ZQ, sign: int = 1) -> ZQ:
    out: ZQ = dict(a)
    for k, v in b.items():
        nv = out.get(k, 0) + sign * v
        if nv == 0:
            out.pop(k, None)
        else:
            out[k] = nv
    return out


def zq_scale(a: ZQ, s: int) -> ZQ:
    if s == 0:
        return {}
    return {k: s * v for k, v in a.items()}


def zq_mul_left_by_q(q: QElt, a: ZQ) -> ZQ:
    """Compute q * a (left multiplication by group element q)."""
    out: ZQ = {}
    for k, v in a.items():
        nk = q_mult(q, k)
        nv = out.get(nk, 0) + v
        if nv == 0:
            out.pop(nk, None)
        else:
            out[nk] = nv
    return out


def zq_mul(a: ZQ, b: ZQ) -> ZQ:
    """Compute a * b in Z[Q]."""
    out: ZQ = {}
    for ka, va in a.items():
        for kb, vb in b.items():
            nk = q_mult(ka, kb)
            nv = out.get(nk, 0) + va * vb
            if nv == 0:
                out.pop(nk, None)
            else:
                out[nk] = nv
    return out


def zq_from_pairs(pairs) -> ZQ:
    out: ZQ = {}
    for q, v in pairs:
        if v == 0:
            continue
        nv = out.get(q, 0) + v
        if nv == 0:
            out.pop(q, None)
        else:
            out[q] = nv
    return out


# Generators as Z[Q] elements
def gen_X() -> ZQ: return {("X", 0): 1}
def gen_Y() -> ZQ: return {("Y", 0): 1}
def gen_c() -> ZQ: return {("", 1): 1}
def gen_one() -> ZQ: return {("", 0): 1}


def X_minus_1() -> ZQ:
    return zq_add(gen_X(), gen_one(), sign=-1)


def c_minus_1() -> ZQ:
    return zq_add(gen_c(), gen_one(), sign=-1)


def Y_minus_1() -> ZQ:
    return zq_add(gen_Y(), gen_one(), sign=-1)


# -----------------------------------------------------------------------------
# Linear algebra over Z: HNF and lattice intersection
# -----------------------------------------------------------------------------
# We encode ZQ elements as vectors in Z^N where N = |Q truncated to length L|.

def basis_index(L: int) -> Tuple[Dict[QElt, int], List[QElt]]:
    Qs = enum_Q(L)
    return {q: i for i, q in enumerate(Qs)}, Qs


def zq_to_vec(a: ZQ, idx: Dict[QElt, int]) -> List[int]:
    v = [0] * len(idx)
    for k, val in a.items():
        if k in idx:
            v[idx[k]] = val
        else:
            # out of truncation; mark by raising
            raise ValueError(f"element {k} out of truncation")
    return v


def vec_to_zq(v: List[int], Qs: List[QElt]) -> ZQ:
    out: ZQ = {}
    for i, x in enumerate(v):
        if x:
            out[Qs[i]] = x
    return out


def hnf(matrix: List[List[int]]) -> List[List[int]]:
    """Compute Hermite Normal Form (row HNF) of a Z-matrix.
    Returns a list of nonzero rows (a basis of the row lattice).
    Uses sympy for correctness."""
    import sympy as sp
    if not matrix:
        return []
    M = sp.Matrix(matrix)
    # Sympy's hnf works on integer matrices.  It returns HNF as M.T.rref()? No.
    # Use sympy.matrices.normalforms.hermite_normal_form.
    from sympy.matrices.normalforms import hermite_normal_form
    # hermite_normal_form expects a matrix whose COLUMNS span the lattice and
    # returns an HNF of the column lattice.  We pass M.T to compute the row
    # lattice HNF, then transpose back.
    H = hermite_normal_form(M.T)
    # H has the same column lattice as M.T, i.e., same row lattice as M.
    Hrows = H.T.tolist()
    # Remove zero rows
    return [r for r in Hrows if any(x != 0 for x in r)]


def lattice_intersection(A_rows: List[List[int]], B_rows: List[List[int]]) -> List[List[int]]:
    """Compute Z-basis for the intersection of row lattices spanned by A_rows
    and B_rows (both in Z^n).  Standard approach: stack A; B with augmentation,
    compute kernel.

    Specifically: for vectors x with x = sum a_i A_i = sum b_j B_j, we have
    sum a_i A_i - sum b_j B_j = 0.  Find integer kernel of the matrix
    [A^T | -B^T] -> the coefficients (a, b) parameterize the intersection.
    Then x = sum a_i A_i.
    """
    import sympy as sp
    if not A_rows or not B_rows:
        return []
    n = len(A_rows[0])
    mA = len(A_rows)
    mB = len(B_rows)
    # Build (mA + mB) x n matrix M with rows A_1, ..., A_mA, -B_1, ..., -B_mB.
    # We want integer (a, b) with a * A + b * (-B) = 0 as a column relation, i.e.,
    # M^T * (a, b)^T = 0 where M has those rows.  Compute integer nullspace of M^T.
    M = sp.Matrix(A_rows + [[-x for x in r] for r in B_rows])  # (mA+mB) x n
    # Integer nullspace of M^T: vectors u in Z^{mA+mB} with M^T u = 0, i.e., u^T M = 0.
    # Equivalently u in left nullspace of M.
    # Use sympy nullspace (over Q) then clear denominators.
    ker = M.T.nullspace()
    inter_rows: List[List[int]] = []
    for v in ker:
        # v is a column vector in Q^{mA+mB}.  Clear denominators.
        from sympy import lcm
        denom = 1
        for x in v:
            denom = sp.ilcm(denom, sp.fraction(x)[1])
        u = [int(x * denom) for x in v]
        a_coeffs = u[:mA]
        # x = sum_i a_i * A_i
        x = [0] * n
        for i, ai in enumerate(a_coeffs):
            if ai == 0:
                continue
            for j in range(n):
                x[j] += ai * A_rows[i][j]
        if any(t != 0 for t in x):
            inter_rows.append(x)
    if not inter_rows:
        return []
    return hnf(inter_rows)


# -----------------------------------------------------------------------------
# Build truncated I_A, I_B, intersection
# -----------------------------------------------------------------------------

def build_left_ideal(generators: List[ZQ], L_mult: int, L_amb: int,
                     idx: Dict[QElt, int]) -> List[List[int]]:
    """Generate the Z-lattice spanned by {q * g : q in Q with |q|<=L_mult, g in generators},
    restricted to the truncation (length L_amb in the ambient).  Returns HNF rows."""
    rows: List[List[int]] = []
    Qmult = enum_Q(L_mult)
    for q in Qmult:
        for g in generators:
            prod = zq_mul_left_by_q(q, g)
            # Restrict to truncation: drop any term outside idx.
            try:
                v = zq_to_vec(prod, idx)
            except ValueError:
                # Out-of-truncation term; skip this generator-multiplier (or drop terms).
                # Drop the offending terms:
                v = [0] * len(idx)
                for k, val in prod.items():
                    if k in idx:
                        v[idx[k]] = val
                # This is a "boundary" element; we still include the truncated version
                # but it represents an inaccurate row.  Mark by skipping if any term
                # was dropped -- safer to skip.
                continue
            rows.append(v)
    return hnf(rows)


def pretty_zq(a: ZQ) -> str:
    if not a:
        return "0"
    terms = []
    for (w, e), v in sorted(a.items(), key=lambda kv: (len(kv[0][0]), kv[0][0], kv[0][1])):
        sym = (w if w else "1") + ("c" if e else "")
        if v == 1:
            terms.append(f"+{sym}")
        elif v == -1:
            terms.append(f"-{sym}")
        elif v > 0:
            terms.append(f"+{v}{sym}")
        else:
            terms.append(f"{v}{sym}")
    s = "".join(terms)
    if s.startswith("+"):
        s = s[1:]
    return s


def main() -> int:
    L_amb = 6   # truncation length for ambient Z[Q]
    L_mult = 4  # truncation for multipliers q
    idx, Qs = basis_index(L_amb)
    N = len(Qs)
    print(f"[G39] Truncation: |Q|_{{<={L_amb}}} = {N} basis elements")

    # I_A: generated (as LEFT ideal) by X-1 and c-1
    print(f"[G39] Building I_A (left ideal of <X-1, c-1>) with L_mult={L_mult}...")
    IA = build_left_ideal([X_minus_1(), c_minus_1()], L_mult, L_amb, idx)
    print(f"        rank(I_A truncated) = {len(IA)}")

    # I_B: generated (as LEFT ideal) by Y-1
    print(f"[G39] Building I_B (left ideal of <Y-1>) with L_mult={L_mult}...")
    IB = build_left_ideal([Y_minus_1()], L_mult, L_amb, idx)
    print(f"        rank(I_B truncated) = {len(IB)}")

    # Intersection
    print(f"[G39] Computing I_A cap I_B...")
    Inter = lattice_intersection(IA, IB)
    print(f"        rank(I_A cap I_B truncated) = {len(Inter)}")

    # Show a few low-weight intersection elements
    print(f"\n[G39] First few HNF basis elements of I_A cap I_B (sorted by support):")
    inter_zq = [vec_to_zq(r, Qs) for r in Inter]
    inter_zq.sort(key=lambda a: (sum(len(w) for (w, _) in a.keys()), len(a)))
    for i, z in enumerate(inter_zq[:8]):
        print(f"  [{i}] {pretty_zq(z)}")

    # --- Test: is g_AB = (X-1)(Y-1) in the intersection?
    XY = zq_mul(X_minus_1(), Y_minus_1())
    YX = zq_mul(Y_minus_1(), X_minus_1())
    print(f"\n[G39] (X-1)(Y-1) = {pretty_zq(XY)}")
    print(f"[G39] (Y-1)(X-1) = {pretty_zq(YX)}")

    # Is g_AB in span(Inter)?
    def in_lattice(v: List[int], rows: List[List[int]]) -> bool:
        if not rows:
            return all(x == 0 for x in v)
        import sympy as sp
        # Check if v is in Z-span of rows: solve a^T M = v with a integer.
        # We do this by extending rows with v and seeing if HNF row count is unchanged.
        before = len(hnf(rows))
        after = len(hnf(rows + [v]))
        return before == after

    try:
        XY_vec = zq_to_vec(XY, idx)
        YX_vec = zq_to_vec(YX, idx)
        print(f"[G39] (X-1)(Y-1) in I_A cap I_B? {in_lattice(XY_vec, Inter)}")
        print(f"[G39] (Y-1)(X-1) in I_A cap I_B? {in_lattice(YX_vec, Inter)}")
    except ValueError as e:
        print(f"  truncation issue: {e}")

    # --- Now the KEY question: is I_A cap I_B cyclic as a LEFT Z[Q]-module?
    # Take g = (X-1)(Y-1).  Generate Z[Q].g (left ideal generated by g) truncated.
    print(f"\n[G39] Building left Z[Q].g for g = (X-1)(Y-1)...")
    ZQg = build_left_ideal([XY], L_mult, L_amb, idx)
    print(f"        rank(Z[Q].g truncated) = {len(ZQg)}")

    # Compare lattices: does Z[Q].g equal I_A cap I_B (truncated)?
    # We check both inclusions via rank comparison after combining.
    combined = hnf(ZQg + Inter)
    print(f"        rank(Z[Q].g + (I_A cap I_B)) = {len(combined)}")
    print(f"        rank(Z[Q].g) = {len(ZQg)}, rank(I_A cap I_B) = {len(Inter)}")
    if len(combined) == len(Inter) and len(combined) == len(ZQg):
        print(f"        -> Z[Q].g = I_A cap I_B (truncated): CYCLIC, generator g_AB")
    elif len(combined) == len(Inter):
        print(f"        -> Z[Q].g subset of I_A cap I_B, but PROPER subset")
        print(f"           (rank deficit {len(Inter)-len(ZQg)})")
    else:
        print(f"        -> something weird")

    # --- Also try g' = (Y-1)(X-1)
    print(f"\n[G39] Building left Z[Q].g' for g' = (Y-1)(X-1)...")
    ZQg2 = build_left_ideal([YX], L_mult, L_amb, idx)
    print(f"        rank(Z[Q].g' truncated) = {len(ZQg2)}")
    combined2 = hnf(ZQg + ZQg2 + Inter)
    print(f"        rank(Z[Q].g + Z[Q].g' + (I_A cap I_B)) = {len(combined2)}")

    # And try with both generators g, g', plus (c-1)(Y-1)
    cY = zq_mul(c_minus_1(), Y_minus_1())
    print(f"\n[G39] Building left Z[Q].(c-1)(Y-1) for h = (c-1)(Y-1) = {pretty_zq(cY)}...")
    ZQh = build_left_ideal([cY], L_mult, L_amb, idx)
    print(f"        rank(Z[Q].h truncated) = {len(ZQh)}")
    combined3 = hnf(ZQg + ZQh + Inter)
    print(f"        rank(Z[Q].g + Z[Q].h + (I_A cap I_B)) = {len(combined3)}")
    if len(combined3) == len(Inter):
        excess = len(Inter) - len(hnf(ZQg + ZQh))
        print(f"        -> Z[Q].g + Z[Q].h subset of I_A cap I_B; deficit {excess}")
        if excess == 0:
            print(f"        ** I_A cap I_B = Z[Q].(X-1)(Y-1) + Z[Q].(c-1)(Y-1)  (2-generator) **")

    # --- Annihilator probe: for g = (X-1)(Y-1), compute Y*g and -g; do they match?
    Yg = zq_mul(gen_Y(), XY)
    Yg_plus_g = zq_add(Yg, XY)
    print(f"\n[G39] Y * g_AB = {pretty_zq(Yg)}")
    print(f"[G39] Y * g_AB + g_AB = {pretty_zq(Yg_plus_g)}")
    if not Yg_plus_g:
        print(f"        -> Y acts as -1 on g_AB.  (Matches v8.0 claim.)")
    else:
        print(f"        -> Y does NOT act as -1 on g_AB.  v8.0 module ID broken.")

    cg = zq_mul(gen_c(), XY)
    cg_plus_g = zq_add(cg, XY)
    print(f"[G39] c * g_AB = {pretty_zq(cg)}")
    print(f"[G39] c * g_AB + g_AB = {pretty_zq(cg_plus_g)}")
    if not cg_plus_g:
        print(f"        -> c acts as -1 on g_AB.")
    else:
        print(f"        -> c does NOT act as -1 on g_AB.  v8.0 module ID broken.")

    # --- Probe (X-1)*g
    Xg = zq_mul(gen_X(), XY)
    Xg_minus_g = zq_add(Xg, XY, sign=-1)
    print(f"[G39] (X-1) * g_AB = {pretty_zq(Xg_minus_g)}")

    # Is (X-1)*g_AB in Z[Q].g_AB?  i.e., is g_AB a generator stable under multiplication?
    try:
        Xg_minus_g_vec = zq_to_vec(Xg_minus_g, idx)
        print(f"[G39] (X-1)*g_AB in Z[Q].g_AB (truncated)? {in_lattice(Xg_minus_g_vec, ZQg)}")
    except ValueError:
        print(f"  truncation issue")

    return 0


if __name__ == "__main__":
    sys.exit(main())
