#!/usr/bin/env python3
"""G39b -- Follow-up.  KEY FINDINGS from G39:
 - (X-1)(Y-1) is NOT in I_A cap I_B (as LEFT ideals).  v8.0 was using
   the wrong candidate generator.
 - The intersection HNF basis is supported only on c-paired elements:
       (1 - c) - Y(1 - c) = (1 - Y)(1 - c)  for the leading term.
 - In fact the basis elements look like  w * (1-c)(1-Y)  with w varying.
   This suggests I_A cap I_B is generated by h = (1-c)(1-Y) as a left ideal.

We test this systematically with larger truncations.
"""
from __future__ import annotations
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from G39_noncomm_ideal import (
    X_minus_1, Y_minus_1, c_minus_1, gen_one, gen_X, gen_Y, gen_c,
    zq_mul, zq_add, zq_scale, zq_mul_left_by_q, pretty_zq,
    basis_index, enum_Q, build_left_ideal, lattice_intersection, hnf,
    zq_to_vec, vec_to_zq,
)


def main() -> int:
    # Truncation parameters
    for L_amb, L_mult in [(8, 6), (10, 7)]:
        print(f"\n========== L_amb={L_amb}, L_mult={L_mult} ==========")
        idx, Qs = basis_index(L_amb)
        N = len(Qs)
        print(f"|Q|_<={L_amb}: {N}")

        IA = build_left_ideal([X_minus_1(), c_minus_1()], L_mult, L_amb, idx)
        IB = build_left_ideal([Y_minus_1()], L_mult, L_amb, idx)
        Inter = lattice_intersection(IA, IB)
        print(f"rank I_A={len(IA)}, rank I_B={len(IB)}, rank Inter={len(Inter)}")

        # Candidate generator: h = (1-c)(1-Y) = 1 - Y - c + cY
        # Equivalently h = -(c-1)(Y-1) = -(cY - c - Y + 1)
        # Let's use h = (c-1)(Y-1) = cY - c - Y + 1 = 1 - c - Y + cY.
        h = zq_mul(c_minus_1(), Y_minus_1())
        print(f"candidate h = (c-1)(Y-1) = {pretty_zq(h)}")

        ZQh = build_left_ideal([h], L_mult, L_amb, idx)
        print(f"rank Z[Q].h = {len(ZQh)}")
        comb = hnf(ZQh + Inter)
        print(f"rank Z[Q].h + Inter = {len(comb)}")
        if len(comb) == len(Inter) and len(comb) == len(ZQh):
            print("=> Z[Q].h = I_A cap I_B   (CYCLIC, single generator h)")
        elif len(comb) == len(Inter):
            print(f"=> Z[Q].h subset Inter; deficit {len(Inter) - len(ZQh)}")
        else:
            print("=> Z[Q].h NOT subset of Inter")

    # ANNIHILATOR of h = (c-1)(Y-1):
    print("\n--- Annihilator of h = (c-1)(Y-1) ---")
    h = zq_mul(c_minus_1(), Y_minus_1())
    print(f"h = {pretty_zq(h)}")

    # (Y+1)*h: should be 0 if Y acts as -1 on h
    Yh = zq_mul(gen_Y(), h)
    Yh_plus_h = zq_add(Yh, h)
    print(f"Y*h = {pretty_zq(Yh)}")
    print(f"Y*h + h = {pretty_zq(Yh_plus_h)}  -> Y acts as -1? {not Yh_plus_h}")

    # (c+1)*h: should be 0 if c acts as -1 on h
    ch = zq_mul(gen_c(), h)
    ch_plus_h = zq_add(ch, h)
    print(f"c*h = {pretty_zq(ch)}")
    print(f"c*h + h = {pretty_zq(ch_plus_h)}  -> c acts as -1? {not ch_plus_h}")

    # X * h
    Xh = zq_mul(gen_X(), h)
    print(f"X*h = {pretty_zq(Xh)}")
    # Is X*h in Z[Q].h?  Need numerical check.

    # ----- Now check directly: does I_A cap I_B = left ideal generated by (c-1)(Y-1)?
    # Equivalently, since c commutes with Y, (c-1)(Y-1) = (Y-1)(c-1) — verify:
    h_alt = zq_mul(Y_minus_1(), c_minus_1())
    diff = zq_add(h, h_alt, sign=-1)
    print(f"\n(c-1)(Y-1) - (Y-1)(c-1) = {pretty_zq(diff)}  (should be 0 since c central)")

    # The relation modules for M = Z[Q]/(Y+1, c+1):
    # In this M, Y*v = -v and c*v = -v.  We've shown h satisfies both. PERFECT.
    # So Z[Q].h is a QUOTIENT of M = Z[Q]/(Y+1, c+1).
    # Question: is it equal to M, or a proper quotient?

    # M has Z-basis {(XY)^k v : k in Z} union {X(YX)^k v}... actually since the
    # quotient kills Y+1 and c+1 from the left in left-module structure:
    #     Y . v = -v,  c . v = -v
    # Any element of Q acts: write q = (alternating word in X,Y) * c^eps.
    # eps factor gives (-1)^eps.  Word w in {X,Y}: if w starts with Y, use Y.v = -v.
    # So M as Z-module has basis indexed by words STARTING with X (or empty),
    # without c (because c is absorbed by sign).
    # Empty word: 1 element (v itself).
    # Length 1: X.v.
    # Length 2: XY.v.   (YX.v = Y.(X.v) — still independent.)
    # Wait — Y . (X.v) = (YX).v in M, no simplification (since Y v = -v applies only
    # at the END, i.e. when Y multiplies on the LEFT of v directly).
    # Hmm — actually in a left module, Y.(X.v) means apply Y to X.v.  And Y.v = -v
    # is the relation, but Y.(X.v) is NOT equal to (YX).v? No it IS: (YX).v = Y.(X.v)
    # by associativity of the left action.  And we cannot simplify YX further because
    # Y v = -v doesn't say (anything)·Y·v has any reduction.
    # So M as Z-module is FREE on { w . v : w alternating word in {X,Y} not ENDING
    # in Y or in c }.  Reason: a word ending in Y gives ... Y . v = (...)·(-v),
    # absorbed into shorter word with sign.  Similarly c at the end gives sign.
    # Words ending in Y or having c can be reduced.
    # Alternating words NOT ending in Y: those ending in X (or empty).
    # So M has Z-basis { v, X.v, XYX.v, YX.v, XYXYX.v, YXYX.v, ...} hmm + empty.
    # Equivalently: words in {X,Y} ending in X (length odd starting with X, or
    # length even ending in X), plus empty.
    # This is countably infinite.

    # Quick sanity check via direct truncated computation of Z[Q].h.

    L_amb = 10
    L_mult = 8
    idx, Qs = basis_index(L_amb)
    h = zq_mul(c_minus_1(), Y_minus_1())
    ZQh = build_left_ideal([h], L_mult, L_amb, idx)
    print(f"\n[L_amb=10,L_mult=8] rank Z[Q].h = {len(ZQh)}")

    # Expected: number of words w of length <= L_amb such that w ends in X or is empty,
    # WITHOUT the c-extension since c just gives sign on h:
    # The basis is w.h where w runs over the elements of Q.  But many w.h coincide.
    # Specifically (Y).h = -h, (c).h = -h, etc.  So w.h depends only on w modulo the
    # relations Y.v = -v, c.v = -v (from the LEFT).
    # i.e. w.h = (-1)^(#trailing Y's and c's removed) (reduced_w).h
    # Net: the *equivalence classes* of w's modulo right-trimming Y and c.
    # That's exactly: alternating words ending in X (plus empty), no c factor.
    # Count up to length L_amb: empty (1) + words of length 1 ending in X (1: "X")
    # + length 2 ending in X (1: "YX") + length 3 ending in X (1: "XYX") + ...
    # = L_amb + 1.

    print(f"Predicted Z-rank of Z[Q].h truncated <= {L_amb}: about {L_amb + 1}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
